name: "devcontainer image name"
description: |
  set up environment variable IMAGE_NAME containing the computed dev container image.
  the dev container image name is constructed from the repository owner/name and the branch name all lowercased.
  example : ghcr.io/IONOS-Wordpress/ionos-wordpress-develop-devcontainer for develop branch

runs:
  using: "composite"
  steps:
    - name: build image name
      shell: bash
      run: |
        # construct image_name from repo owner/name and branch
        # example value : "ghcr.io/IONOS-Wordpress/ionos-wordpress-develop-devcontainer"
        image_name="ghcr.io/${GITHUB_REPOSITORY}-${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}-devcontainer"
        # convert image_name to lowercase and provide it as step variable "image_name"
        echo "image_name=${image_name@L}" >> $GITHUB_OUTPUT
