version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/packages/npm/*'
      - '/packages/wp-plugin/*'
    versioning-strategy: 'increase'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'docker'
    directories:
      - '/packages/docker/*'
    versioning-strategy: 'increase'
    schedule:
      interval: 'weekly'
