version: 2
updates:
  - package-ecosystem: 'npm'
    directories:
      - '/'
      - '/packages/npm/*'
      - '/packages/wp-plugin/*'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'docker'
    directories:
      - '/packages/docker/*'
    schedule:
      interval: 'weekly'
