name: "devcontainer shell run"
description: |
  set up computed dev container image and run a command within the dev container.
inputs:
  runCmd:
    description: 'the command(s) to execute using the image'
    required: true
    default: 'echo "WP_ENV_HOME=${WP_ENV_HOME} !"'
outputs:
  runCmdOutput:
    description: "the output of the command"
    value: ${{ steps.devcontainer_shell_run.outputs.runCmdOutput }}

runs:
  using: "composite"
  steps:
    - uses: "./.github/shared/actions/devcontainer-image-name"
      id: image_name

    - uses: devcontainers/ci@v0.3
      id: devcontainer_shell_run
      with:
        push: never
        cacheFrom: ${{ steps.image_name.outputs.image_name }}
        runCmd: ${{ inputs.runCmd }}

