name: Build DevContainer Image
on:
  workflow_call:

    # secrets:
    #   GITHUB_TOKEN:
    #     required: true

    # map the workflow outputs to job outputs
    outputs:
      image_name:
        value: ${{ jobs.build.image_name }}
      all:
        value: ${{ toJson(jobs) }}

permissions:
  # write-all is too much, but we need to write to packages
  # see https://github.com/orgs/community/discussions/57724 for more info
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.image_name.outputs.image_name }}
      baldrian: "schmeckt nicht"
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: "./.github/shared/actions/devcontainer-image-name"
        id: image_name

      - name: Build dev container and push to GitHub Container Registry
        uses: devcontainers/ci@v0.3
        with:
          # push image only if the branch is main and the event is push
          push: filter
          refFilterForPush: |
            refs/heads/main
            refs/heads/develop
          eventFilterForPush: |
            push
          imageName: ${{ steps.image_name.outputs.image_name }}


