name: 'release'

on:
  # rebuild any PRs and main branch changes
  pull_request:

  push:
    branches:
      - main
      - develop

permissions:
  # write-all is too much, but we need to write to packages
  # see https://github.com/orgs/community/discussions/57724 for more info
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    needs:
      - build-dev-container-image
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: display output name
        run: echo "image_name=${{ jobs.build_dev_container_image.outputs.image_name }}"

  build-dev-container-image:
    uses: ./.github/workflows/build-devcontainer-image.yaml

